### ISSUE TITLE
homeassistant LED device - Add HTTPS support

### ISSUE THREAD

**Issue by Z3r10** [hyperion-project/hyperion.ng#1886]
#### What problem does this feature solve?
Add HTTPS support to the homeassistant LED device.

At the moment, the log reports that hyperion-ng tries to connect through http only, with no visible option (GUI or file) to enable HTTPS.
HTTPS is a standard, and for those who have enabled HTTP at the config level (not through reverse-proxy), there is no way to bypass it.
Connection is simply refused by HA.

#### What does the proposed API look like?
N/A - already implemented

#### How should this be implemented in your opinion?
* Short-term: Add HTTPS support, with option to bypass SSL related errors to handle self-signed certs
* Long-term: Add the option to trust custom CA Certs.

#### Are you willing to work on this yourself?
No. I don't have the knowledge to.

**Comment by josh-blake** [comment]
+1 for this; Hyperion.ng homeassistant plugin does not attempt connection to HA via SSL and instead attempts connection over http which I do not (intentionally) have enabled on my HA instance.

**Comment by WybeBosch** [comment]
Ah damm.. i hoped there was some way to enable SSL on the request T_T

I just switched my homeassistant over to https, and now i find this.. rip.

**Comment by WybeBosch** [comment]
I ended up running a small nginx bridge on my raspberrypi. Just direct the hyperion to there, and the bridge will forward it to the homeassistant running the https version of homeassistant.

**Comment by Lord-Grey** [comment]
Let me maybe better understand the movtivation of the feature request...
Are you looking for https support, because the "s" gives you security or are you following an overall network security concept.
I am, by no means, a security exepert, but for the later I would see some conflicting messages in the above.

Let me share my train of throughs...

Normally, you would trust traffic in your local network segement and secure access to the outside.
This would mean you would run HA with http and, if you need to access it from remote, you would publish an https enpoint with a proper certificate provided by an official CA, e.g. Let's Encrypt. To map to http-HA you would set up a reverse proxy which terminates external connections in a defined way.
I am running my HA as a container on a Synology NAS and setting up a https reverse proxy is a 2 minutes thing.

Nevertheles, if you do not want to go the reverse proxy route, you still would configre HA with a certificate signed by an official CA.
I do not get why you weaken your security by self-signed certifictes. Either you go the full route or not.
If you are afraid someone access HA or reads traffic, then the risk to intercept the self-signed certificate is not far away.

I am ok to look how https protocol can be switched going forward, but I do not get the benefit for self-signed certificates, if you take security seriously.

Edit: Before looking into this one, I first need to fix the general issue with network devices request messages.

**Comment by Z3r10** [comment]
Hi @Lord-Grey,

Thank you for your extensive answer, which I agree with.
I'm in another situation: I have my own internal CA.
I connect to HA through VPN so all could be considered "internal" traffic, but still, I try to issue and manage Certs for all critical servers I have: HA is one of them considering all the data it processes.

On my side, HTTP is simply not reachable anymore on HA, and all traffic is firewalled (only used ports are allowed).

In fact adding the option to import and trust CA Cert would be even better, but for now I'm not asking for this much. simple HTTPS connection would be okay 😊

**Comment by josh-blake** [comment]
Sorry, I think everyone here is missing the point. Irrespective of how one sets up their SSL configuration, the plugin currently does not support connecting via HTTPS. And, there is no way to connect to an instance natively using SSL over clear text without using some reverse nginx hack like WybeBosch has above.

My instance uses a LE certificate directly without all the reverse proxy stuff because content sent over my network, amongst other things, should be encrypted. That WEP2/3 is trivially insecure and that I live in a large urban environment is enough to dictate this.

Just because one person does not enable HTTPS on their HA server directly does not mean that we should be poo-pooing on others that do, or somehow invalidating the reasons why. Simply put, HA is designed to be spun up in many configurations. That the HA plugin for Hyperion/HyperHDR did not reflect HTTPS by default simply speaks to the likely configuration the original code writer was using.

Nevertheless I have changed the code to break out the feature; see this PR: https://github.com/awawa-dev/HyperHDR/pull/1249

I have rewritten part of ProviderRestApi module to enable the constructor to accept a useHTTPS bool argument. In reality, this simply specifies 'https' rather than 'http' for the underlying QTNetwork framework. This addition adds portability to the codebase and allows other modules to follow suit should they take advantage of this. I have removed the logic that assumes a connection on port 443 is ALWAYS HTTPS in the constructor method. This is dangerous. You must explicitly specify to the method that you wish to use SSL, otherwise it assumes HTTP insecure. Ceebs to making a QUrl that auto-figures-out-the-host/port/scheme.

Having said this QT6 completely refactors the networking stack and so I would imagine this will have to change at some point.

Anyways, after having a bit of a play around, I find the plugin slow. It accesses the HA API at a balmy 1-2 updates per second. I will probably look instead to implementing the RawUDP protocol to directly control my LIFX bulbs.

**Comment by Lord-Grey** [comment]
@josh-blake I at no point questioned the requirement that https should be supported and people are able to switch. My only point was on self signed certificates usage.

Btw. There is not even the need to update constructors. Just do a setScheme("https") after object creation and you are there.

**Comment by WybeBosch** [comment]
Nice to see such interest in this feature request :D and that @josh-blake has already started on a PR. 

Il add as another note that, while the default install of homeassitant is indeed http
there are some default features in homeassistant that REQUIRE https, thus i would say that most homeassistant users will eventually upgrade to https. Making the need for such a feature more of a requirement.

**Comment by Lord-Grey** [comment]
I implemented the HA https support.
Would you mind testing https://github.com/hyperion-project/hyperion.ng/pull/1884?

For testing PRs see https://docs.hyperion-project.org/user/advanced/Testing.html

**Comment by Lord-Grey** [comment]
Fixed by #1884

**Comment by WybeBosch** [comment]
> Fixed by [#1884](https://github.com/hyperion-project/hyperion.ng/pull/1884)

I compiled the master branch of hyperion locally, and manage to test that the burst request issue was solved. 

As for the HTTPS support being added, i thought this would be a toggle or something. 
Im not quite sure how it activates right now? 

when i put the local ip adress with https, it still gets quite mad

<img width="691" height="592" alt="Image" src="https://github.com/user-attachments/assets/929f5ad5-8538-4676-a9e7-6a23dabd441d" />

Same for the actual domain that is reachable (Not my actual domain in the image, but you get the point)

<img width="694" height="586" alt="Image" src="https://github.com/user-attachments/assets/8137aaf8-626f-434b-93e3-69eb96e61acb" />


for now il just keep my little nginx https bridge on the pi. That seems to work. 
And i have some other things to figure out on my end first light wise anyways.

**Comment by josh-blake** [comment]
> > Fixed by [#1884](https://github.com/hyperion-project/hyperion.ng/pull/1884)
> 
> I compiled the master branch of hyperion locally, and manage to test that the burst request issue was solved.
> 
> As for the HTTPS support being added, i thought this would be a toggle or something. Im not quite sure how it activates right now?
> 
> when i put the local ip adress with https, it still gets quite mad
> 
> <img alt="Image" width="691" height="592" src="https://private-user-images.githubusercontent.com/40889930/482328813-929f5ad5-8538-4676-a9e7-6a23dabd441d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYyNDQyNzcsIm5iZiI6MTc1NjI0Mzk3NywicGF0aCI6Ii80MDg4OTkzMC80ODIzMjg4MTMtOTI5ZjVhZDUtODUzOC00Njc2LWE5ZTctNmEyM2RhYmQ0NDFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODI2VDIxMzI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4N2Q3YjIyMTk5NGU0Nzc5YmI0Y2FjNmZiMDUyZWQ2OGE0OTEwNzc3MzM4Yjc3ZTg1Y2Q2MDg3NmM2NDdlYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VRIVNzRsrUhwHWFyJf8xjliQWaPLlR46XWoKYMj2uWY">
> Same for the actual domain that is reachable (Not my actual domain in the image, but you get the point)
> 
> <img alt="Image" width="694" height="586" src="https://private-user-images.githubusercontent.com/40889930/482329530-8137aaf8-626f-434b-93e3-69eb96e61acb.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYyNDQyNzcsIm5iZiI6MTc1NjI0Mzk3NywicGF0aCI6Ii80MDg4OTkzMC80ODIzMjk1MzAtODEzN2FhZjgtNjI2Zi00MzRiLTkzZTMtNjllYjk2ZTYxYWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODI2VDIxMzI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NWI0OTc2ZDY3NzQ0ZjYyNWNjYmNjMzUxMzMyYjg2ODdkYmZmYTlhOWU2NmZiZGM4MDllZjRjNjVmY2I0MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BM9QV48Lkj6YuEZxjxuIGseNuvyIl-y5QaJwNtRXGHs">
> for now il just keep my little nginx https bridge on the pi. That seems to work. And i have some other things to figure out on my end first light wise anyways.

You are not using the domain name attached to your certificate. It will fail as a consequence. You must reference your instance by name and not IP, and make sure your ports are forwarded correctly. If you have set up an NGINX reverse proxy, don’t forget that you would have set up a hedder-referrer restriction in HA. You will need to tear that down too for your trial.

**Comment by Lord-Grey** [comment]
> when i put the local ip address with https, it still gets quite mad

Do not put the „https“ protocol scheme into the hostname field. Hostname is hostname and not a url, this what the error says.

… and as Josh pointed out, you need to put the DNS hostname which is part of your certificate (signed by an official CA)

Enable minimum Advanced settings and then you can enable SSL.

**Comment by Z3r10** [comment]
I just installed 2.2.0 yesterday and finally managed to connect through HTTPS.
(I did not test the nightly).

Thanks, everything worked fine, many thanks for it! :)

Additionally, I would like to share a little tuto to make it work with custom CA:
🌐 [HTTPS Connection to Home Assistant (or other) with Custom CA Certificate](https://github.com/orgs/hyperion-project/discussions/1986#discussion-9549715)
